pipeline {
    agent any 
    stages {
    stage('maven -e install') {
      steps {
        dir('/home/vagrant/.jenkins/workspace/test-maven-pipeline/complete-jenkins/sample-maven-project/') {
          withMaven(maven: 'Maven3') {
            sh 'mvn clean install'
          }
        }
      }  
    }
  }
}